### ISSUE TITLE
Reference spritemap.svg fragment directly from css?

### ISSUE THREAD

**Issue by illepic** [cascornelissen/svg-spritemap-webpack-plugin#72]
This may likely be a Webpack question, but:

How would we reference a fragment of the spritemap directly in any CSS file? ie

```css
.thingy {
  content: url('spritemap.svg#sprite-thingy');
}
```
